### ISSUE TITLE
Add `run` command functionality

### ISSUE THREAD

**Issue by johnmosesman** [daemonsy/hubot-heroku#24]
Hey there,

Based on this line from the README:

"Only use Heroku's Platform API, no direct running of commands in Bash"

Would adding behavior to run rake tasks fall under this? For example using hubot to kick off a `heroku run rake blah`. If that would work, I'd be interested in making a PR for it.

**Comment by daemonsy** [comment]
Hey @johnmosesman, Heroku's platform API does have a command to do `run`, that's what `hubot heroku migrate <app>` is powered by. However, I didn't include a `hubot heroku run <any command>` because it's potentially destructive. 

I think it's an acceptable use case to do `hubot heroku run rake <task>` command. Would you like to do a PR for this?

**Comment by johnmosesman** [comment]
@daemonsy Yeah I'd love to! I'll get on it.

**Comment by johnmosesman** [comment]
@daemonsy So sorry I haven't gotten anything to you yet on this, but I am starting now!
